name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Install mpfr
      run: sudo apt-get install gcc-10 libmpfr-dev libmpc-dev

    - name: Build libgccjit
      run: |
        mkdir -p artifact
        
        echo "some_test" >> artifact/libgccjit.so
        echo "some_test" >> artifact/check


    - uses: actions/upload-artifact@v2
      with:
          name: libgccjit.so
          path: artifact
